### ISSUE TITLE
Plugin Activation

### ISSUE THREAD

**Issue by FractalArt** [KiranWells/micro-nord-tc-colors#2] opened 2020-12-13 15:29 UTC
I am new to `micro` and installed this plugin via the command mentioned on the plugins page:

```
> micro -plugin install nord-colors
```
which creates the directory *~/.config/micro/plug/nord-colors/*. However, I don't seem to be able to activate it. My first attempt was to run 

```
> set colorscheme nord-colors
```

which resulted in `nord-colors is not a valid colorscheme`. Inspecting the created directory, I saw that the definition files seemed to be of the form `nord-16.micro`

so I also tried

```
> set colorscheme nord-16
```

which resulted in the same error. Would you mind clarifying how I can "activate" the nord colors? Maybe it works differently since this is considered a plugin and not a colorscheme.

**Comment by KiranWells** [comment] 2020-12-13 17:55
I am aware of this issue and am trying to fix it. The issue is that the .lua file that is supposed to add the colorscheme files to micro is not running correctly. Until I figure it out, you can manually install by moving the colorschemes (.micro files) to the colorschemes directory. 
```bash
mkdir ~/.config/micro/colorschemes
mv ~/.config/micro/plug/nord-colors/*.micro ~/.config/micro/colorschemes
```

**Comment by FractalArt** [comment] 2020-12-13 18:01
Perfect, that works.

Thanks a lot for your help!

**Comment by KiranWells** [comment] 2020-12-13 18:33
The issue still seems to exist, even with the new .lua file. This may take some time to fix, until then, anyone who has this issue can use the commands listed above to manually enable the colorschemes.

**Comment by KiranWells** [comment] 2020-12-14 02:54
The issue is now fixed; make sure to run the `nordsetup` command to set up the files after installation. I will make an issue on the main Micro GitHub later to address the issue of runtime files not being visible at startup.

**Closed as completed by KiranWells** 2020-12-14 02:54 UTC

**Comment by zyedidia** [comment] 2020-12-20 06:07
You should be able to use `AddRuntimeFile` similar to how it is done here: https://github.com/Theodus/micro-monokai-dark. Is there a problem with that method?

**Comment by KiranWells** [comment] 2020-12-20 19:31
Unfortunately, using `AddRuntimeFile` runs *after* micro checks for the colorscheme, so it always says `nord-tc is not a valid colorscheme` even when I can enable it directly after. Also, using `AddRuntineFile` as the other plugins do without importing micro/config leads to a lua error, since it is not defined. 

I can post a more detailed issue on the micro main channel if you would like.

**Comment by zyedidia** [comment] 2020-12-20 19:54
I think it should work fine if you run it in the script top-level (not inside the init function). For example:

```lua
VERSION = "1.1.3"

local config = import("micro/config")

config.AddRuntimeFile("nordcolors", config.RTColorscheme, "colorschemes/nord-tc.micro")
config.AddRuntimeFile("nordcolors", config.RTColorscheme, "colorschemes/nord-tc-light.micro")
config.AddRuntimeFile("nordcolors", config.RTColorscheme, "colorschemes/nord-16.micro")
config.AddRuntimeFile("nordcolors", config.RTColorscheme, "colorschemes/nord-16-light.micro")
config.AddRuntimeFile("nordcolors", config.RTHelp, "help/nordcolors.md")
```

**Comment by KiranWells** [comment] 2020-12-20 23:36
I will check that to make sure
